server:
  port: 8080

spring:
  data:
    mongodb:
      database: qualita
      uri: mongodb+srv://admin:admin@cluster0.mmz1f.mongodb.net/qualita-prod?retryWrites=true&w=majority

admin:
  email: advogadosgorla@gmail.com